# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firend_of',
            field=models.ManyToManyField(related_name='_user_firend_of_+', to='friendsapp.User'),
        ),
    ]
